// Captures every booth view for visual review: node tools/views.mjs [prefix]
import { chromium } from 'playwright-core';
const pre = process.argv[2] || 'v';
const browser = await chromium.launch({ executablePath: '/Applications/Google Chrome.app/Contents/MacOS/Google Chrome', headless: true, args: ['--use-angle=metal', '--enable-gpu', '--ignore-gpu-blocklist'] });
const page = await browser.newPage({ viewport: { width: 1600, height: 900 } });
const errs = [];
page.on('pageerror', (e) => errs.push(e.message));
page.on('console', (m) => { if (m.type() === 'error') errs.push(m.text()); });
const shot = (n) => page.screenshot({ path: `shots/${pre}-${n}.png` });
await page.goto('http://localhost:5240/');
await page.waitForFunction(() => window.__ready);
await page.waitForTimeout(2500);
await shot('title');
await page.goto('http://localhost:5240/?day=4&case=1');
await page.waitForFunction(() => window.__ready);
await page.waitForTimeout(1200);
await shot('load');
await page.waitForTimeout(2600);
await shot('focus');
await page.keyboard.press('w');
await page.waitForTimeout(1300);
await shot('desk');
await page.keyboard.press('q');
await page.waitForTimeout(1000);
await page.keyboard.press('c');
await page.waitForTimeout(700);
await shot('cam2');
await page.keyboard.press('e');
await page.waitForTimeout(1200);
await page.click('.stk.off >> nth=0');
await page.click('.tab >> text=Match');
await page.click('.stk.shirt >> nth=14');
await page.click('.tab >> text=Actions');
await page.click('.stk.card >> nth=0');
await page.click('.stk.restart >> nth=2');
await page.waitForTimeout(400);
await shot('tape');
await page.click('.send');
await page.waitForTimeout(1500);
await shot('send0');
await page.waitForTimeout(1600);
await shot('send1');
await page.waitForTimeout(2200);
await shot('send2');
await page.waitForTimeout(2300);
await shot('send3');
await page.waitForSelector('.verdict', { timeout: 20000 });
await page.waitForTimeout(900);
await shot('verdict');
console.log('errors', errs);
await browser.close();
